name: C/C++ CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: sudo apt install -y build-essential
      - name: criterion config
        run: sudo apt-get install -y libcriterion-dev
      - name: Compile files
        run: |
          gcc -o test1 test1.c.test -lcriterion
      - name: Run program
        run: ./test1
      - name: Compile test 2
        run: |
          gcc -o test2 folder/test2.c.test -lcriterion
      - name: Run test 2
        run: |
          cd folder/
          ./test2
